/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransposeRouteImport } from './routes/transpose'
import { Route as TraceRankRouteImport } from './routes/trace-rank'
import { Route as StructureToolsRouteImport } from './routes/structure-tools'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as ScalarRouteImport } from './routes/scalar'
import { Route as RrefRouteImport } from './routes/rref'
import { Route as PowerRouteImport } from './routes/power'
import { Route as NormsMetricsRouteImport } from './routes/norms-metrics'
import { Route as MatrixProductsRouteImport } from './routes/matrix-products'
import { Route as MatrixExponentialRouteImport } from './routes/matrix-exponential'
import { Route as LinearSystemRouteImport } from './routes/linear-system'
import { Route as InverseRouteImport } from './routes/inverse'
import { Route as GeneratorsRouteImport } from './routes/generators'
import { Route as ElementwiseRouteImport } from './routes/elementwise'
import { Route as EigenCharacteristicRouteImport } from './routes/eigen-characteristic'
import { Route as DeterminantRouteImport } from './routes/determinant'
import { Route as DecompositionsRouteImport } from './routes/decompositions'
import { Route as AdvancedProductsRouteImport } from './routes/advanced-products'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'

const TransposeRoute = TransposeRouteImport.update({
  id: '/transpose',
  path: '/transpose',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceRankRoute = TraceRankRouteImport.update({
  id: '/trace-rank',
  path: '/trace-rank',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureToolsRoute = StructureToolsRouteImport.update({
  id: '/structure-tools',
  path: '/structure-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ScalarRoute = ScalarRouteImport.update({
  id: '/scalar',
  path: '/scalar',
  getParentRoute: () => rootRouteImport,
} as any)
const RrefRoute = RrefRouteImport.update({
  id: '/rref',
  path: '/rref',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerRoute = PowerRouteImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => rootRouteImport,
} as any)
const NormsMetricsRoute = NormsMetricsRouteImport.update({
  id: '/norms-metrics',
  path: '/norms-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixProductsRoute = MatrixProductsRouteImport.update({
  id: '/matrix-products',
  path: '/matrix-products',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixExponentialRoute = MatrixExponentialRouteImport.update({
  id: '/matrix-exponential',
  path: '/matrix-exponential',
  getParentRoute: () => rootRouteImport,
} as any)
const LinearSystemRoute = LinearSystemRouteImport.update({
  id: '/linear-system',
  path: '/linear-system',
  getParentRoute: () => rootRouteImport,
} as any)
const InverseRoute = InverseRouteImport.update({
  id: '/inverse',
  path: '/inverse',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorsRoute = GeneratorsRouteImport.update({
  id: '/generators',
  path: '/generators',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementwiseRoute = ElementwiseRouteImport.update({
  id: '/elementwise',
  path: '/elementwise',
  getParentRoute: () => rootRouteImport,
} as any)
const EigenCharacteristicRoute = EigenCharacteristicRouteImport.update({
  id: '/eigen-characteristic',
  path: '/eigen-characteristic',
  getParentRoute: () => rootRouteImport,
} as any)
const DeterminantRoute = DeterminantRouteImport.update({
  id: '/determinant',
  path: '/determinant',
  getParentRoute: () => rootRouteImport,
} as any)
const DecompositionsRoute = DecompositionsRouteImport.update({
  id: '/decompositions',
  path: '/decompositions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedProductsRoute = AdvancedProductsRouteImport.update({
  id: '/advanced-products',
  path: '/advanced-products',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/advanced-products': typeof AdvancedProductsRoute
  '/decompositions': typeof DecompositionsRoute
  '/determinant': typeof DeterminantRoute
  '/eigen-characteristic': typeof EigenCharacteristicRoute
  '/elementwise': typeof ElementwiseRoute
  '/generators': typeof GeneratorsRoute
  '/inverse': typeof InverseRoute
  '/linear-system': typeof LinearSystemRoute
  '/matrix-exponential': typeof MatrixExponentialRoute
  '/matrix-products': typeof MatrixProductsRoute
  '/norms-metrics': typeof NormsMetricsRoute
  '/power': typeof PowerRoute
  '/rref': typeof RrefRoute
  '/scalar': typeof ScalarRoute
  '/spaces': typeof SpacesRoute
  '/structure-tools': typeof StructureToolsRoute
  '/trace-rank': typeof TraceRankRoute
  '/transpose': typeof TransposeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/advanced-products': typeof AdvancedProductsRoute
  '/decompositions': typeof DecompositionsRoute
  '/determinant': typeof DeterminantRoute
  '/eigen-characteristic': typeof EigenCharacteristicRoute
  '/elementwise': typeof ElementwiseRoute
  '/generators': typeof GeneratorsRoute
  '/inverse': typeof InverseRoute
  '/linear-system': typeof LinearSystemRoute
  '/matrix-exponential': typeof MatrixExponentialRoute
  '/matrix-products': typeof MatrixProductsRoute
  '/norms-metrics': typeof NormsMetricsRoute
  '/power': typeof PowerRoute
  '/rref': typeof RrefRoute
  '/scalar': typeof ScalarRoute
  '/spaces': typeof SpacesRoute
  '/structure-tools': typeof StructureToolsRoute
  '/trace-rank': typeof TraceRankRoute
  '/transpose': typeof TransposeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/advanced-products': typeof AdvancedProductsRoute
  '/decompositions': typeof DecompositionsRoute
  '/determinant': typeof DeterminantRoute
  '/eigen-characteristic': typeof EigenCharacteristicRoute
  '/elementwise': typeof ElementwiseRoute
  '/generators': typeof GeneratorsRoute
  '/inverse': typeof InverseRoute
  '/linear-system': typeof LinearSystemRoute
  '/matrix-exponential': typeof MatrixExponentialRoute
  '/matrix-products': typeof MatrixProductsRoute
  '/norms-metrics': typeof NormsMetricsRoute
  '/power': typeof PowerRoute
  '/rref': typeof RrefRoute
  '/scalar': typeof ScalarRoute
  '/spaces': typeof SpacesRoute
  '/structure-tools': typeof StructureToolsRoute
  '/trace-rank': typeof TraceRankRoute
  '/transpose': typeof TransposeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/advanced-products'
    | '/decompositions'
    | '/determinant'
    | '/eigen-characteristic'
    | '/elementwise'
    | '/generators'
    | '/inverse'
    | '/linear-system'
    | '/matrix-exponential'
    | '/matrix-products'
    | '/norms-metrics'
    | '/power'
    | '/rref'
    | '/scalar'
    | '/spaces'
    | '/structure-tools'
    | '/trace-rank'
    | '/transpose'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/advanced-products'
    | '/decompositions'
    | '/determinant'
    | '/eigen-characteristic'
    | '/elementwise'
    | '/generators'
    | '/inverse'
    | '/linear-system'
    | '/matrix-exponential'
    | '/matrix-products'
    | '/norms-metrics'
    | '/power'
    | '/rref'
    | '/scalar'
    | '/spaces'
    | '/structure-tools'
    | '/trace-rank'
    | '/transpose'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/advanced-products'
    | '/decompositions'
    | '/determinant'
    | '/eigen-characteristic'
    | '/elementwise'
    | '/generators'
    | '/inverse'
    | '/linear-system'
    | '/matrix-exponential'
    | '/matrix-products'
    | '/norms-metrics'
    | '/power'
    | '/rref'
    | '/scalar'
    | '/spaces'
    | '/structure-tools'
    | '/trace-rank'
    | '/transpose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AdvancedProductsRoute: typeof AdvancedProductsRoute
  DecompositionsRoute: typeof DecompositionsRoute
  DeterminantRoute: typeof DeterminantRoute
  EigenCharacteristicRoute: typeof EigenCharacteristicRoute
  ElementwiseRoute: typeof ElementwiseRoute
  GeneratorsRoute: typeof GeneratorsRoute
  InverseRoute: typeof InverseRoute
  LinearSystemRoute: typeof LinearSystemRoute
  MatrixExponentialRoute: typeof MatrixExponentialRoute
  MatrixProductsRoute: typeof MatrixProductsRoute
  NormsMetricsRoute: typeof NormsMetricsRoute
  PowerRoute: typeof PowerRoute
  RrefRoute: typeof RrefRoute
  ScalarRoute: typeof ScalarRoute
  SpacesRoute: typeof SpacesRoute
  StructureToolsRoute: typeof StructureToolsRoute
  TraceRankRoute: typeof TraceRankRoute
  TransposeRoute: typeof TransposeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transpose': {
      id: '/transpose'
      path: '/transpose'
      fullPath: '/transpose'
      preLoaderRoute: typeof TransposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace-rank': {
      id: '/trace-rank'
      path: '/trace-rank'
      fullPath: '/trace-rank'
      preLoaderRoute: typeof TraceRankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure-tools': {
      id: '/structure-tools'
      path: '/structure-tools'
      fullPath: '/structure-tools'
      preLoaderRoute: typeof StructureToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scalar': {
      id: '/scalar'
      path: '/scalar'
      fullPath: '/scalar'
      preLoaderRoute: typeof ScalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rref': {
      id: '/rref'
      path: '/rref'
      fullPath: '/rref'
      preLoaderRoute: typeof RrefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power': {
      id: '/power'
      path: '/power'
      fullPath: '/power'
      preLoaderRoute: typeof PowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/norms-metrics': {
      id: '/norms-metrics'
      path: '/norms-metrics'
      fullPath: '/norms-metrics'
      preLoaderRoute: typeof NormsMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix-products': {
      id: '/matrix-products'
      path: '/matrix-products'
      fullPath: '/matrix-products'
      preLoaderRoute: typeof MatrixProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix-exponential': {
      id: '/matrix-exponential'
      path: '/matrix-exponential'
      fullPath: '/matrix-exponential'
      preLoaderRoute: typeof MatrixExponentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linear-system': {
      id: '/linear-system'
      path: '/linear-system'
      fullPath: '/linear-system'
      preLoaderRoute: typeof LinearSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inverse': {
      id: '/inverse'
      path: '/inverse'
      fullPath: '/inverse'
      preLoaderRoute: typeof InverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generators': {
      id: '/generators'
      path: '/generators'
      fullPath: '/generators'
      preLoaderRoute: typeof GeneratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elementwise': {
      id: '/elementwise'
      path: '/elementwise'
      fullPath: '/elementwise'
      preLoaderRoute: typeof ElementwiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eigen-characteristic': {
      id: '/eigen-characteristic'
      path: '/eigen-characteristic'
      fullPath: '/eigen-characteristic'
      preLoaderRoute: typeof EigenCharacteristicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/determinant': {
      id: '/determinant'
      path: '/determinant'
      fullPath: '/determinant'
      preLoaderRoute: typeof DeterminantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decompositions': {
      id: '/decompositions'
      path: '/decompositions'
      fullPath: '/decompositions'
      preLoaderRoute: typeof DecompositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced-products': {
      id: '/advanced-products'
      path: '/advanced-products'
      fullPath: '/advanced-products'
      preLoaderRoute: typeof AdvancedProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AdvancedProductsRoute: AdvancedProductsRoute,
  DecompositionsRoute: DecompositionsRoute,
  DeterminantRoute: DeterminantRoute,
  EigenCharacteristicRoute: EigenCharacteristicRoute,
  ElementwiseRoute: ElementwiseRoute,
  GeneratorsRoute: GeneratorsRoute,
  InverseRoute: InverseRoute,
  LinearSystemRoute: LinearSystemRoute,
  MatrixExponentialRoute: MatrixExponentialRoute,
  MatrixProductsRoute: MatrixProductsRoute,
  NormsMetricsRoute: NormsMetricsRoute,
  PowerRoute: PowerRoute,
  RrefRoute: RrefRoute,
  ScalarRoute: ScalarRoute,
  SpacesRoute: SpacesRoute,
  StructureToolsRoute: StructureToolsRoute,
  TraceRankRoute: TraceRankRoute,
  TransposeRoute: TransposeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
